User.create!(email: "jack@jack.admin", password: 'password', first_name: "Jack", last_name: "Admin", roles: ['admin'])
User.create!(email: "ishmam@ishmam.admin", password: 'password', first_name: "Ishmam", last_name: "Admin", roles: ['admin'])
User.create!(email: "tim@tim.admin", password: 'password', first_name: "Tim", last_name: "Admin", roles: ['admin'])
User.create!(email: "jack@jack.owner", password: 'password', first_name: "Jack", last_name: "Owner", roles: ['owner'])
User.create!(email: "ishmam@ishmam.owner", password: 'password', first_name: "Ishmam", last_name: "Owner", roles: ['owner'])
User.create!(email: "tim@tim.owner", password: 'password', first_name: "Tim", last_name: "Owner", roles: ['owner'])
User.create!(email: "user@user.user", password: 'password', first_name: "User", last_name: "Regular", roles: ['user'])
